Update a position on item tap
vdor/react-native-horizontal-picker pull request #2
Opened 2020-11-03 20:54 UTC by badkos

Calling `onChange` when the item was tapped.

2020-11-03 23:30 UTC, vdor commented
@badkos - Thank you!

Can you update the code to this?
`
if (this.props.onChange != null) {
      this.props.onChange(position);
}
`

Also, please remove the call of `onChange` in the function `setDelayedSnap`. (line 141) and from the line 134.

2020-11-03 23:33 UTC, vdor requested changes

2020-11-03 23:33 UTC, vdor commented on src/index.tsx
> +    if (onChange != null) {
`this.props.onChange`

2020-11-03 23:33 UTC, vdor commented on src/index.tsx
> +      onChange(position);
this.props.onChange

2020-11-04 06:11 UTC, badkos commented
@vdor  I apologize for the inattention

2020-11-04 21:03 UTC, merged